### ISSUE TITLE
Compilation error on d1_mini: SO_RCVTIMEO not declared

### ISSUE THREAD

**Issue by bjw-s** [tube0013/esphome-stream-server-v2#1]
Hi!

I was trying to use this component instead of the one provided by https://github.com/oxan/esphome-stream-server to expose the uart on one of my Wemos D1 mini boards. Unfortunately I am getting an error when compiling the firmware:

```console
src/esphome/components/stream_server/stream_server.cpp: In member function 'virtual void StreamServerComponent::setup()':
src/esphome/components/stream_server/stream_server.cpp:48:43: error: 'SO_RCVTIMEO' was not declared in this scope; did you mean 'LWIP_SO_RCVTIMEO'?
   48 |     this->socket_->setsockopt(SOL_SOCKET, SO_RCVTIMEO, (char *)&timeout, sizeof(timeout));
      |                                           ^~~~~~~~~~~
      |                                           LWIP_SO_RCVTIMEO
Compiling .pioenvs/hallway_p1reader/src/esphome/components/time/real_time_clock.cpp.o
Compiling .pioenvs/hallway_p1reader/src/esphome/components/uart/uart.cpp.o
*** [.pioenvs/hallway_p1reader/src/esphome/components/stream_server/stream_server.cpp.o] Error 1
```

This is on a fresh build of the following config:

```yaml
esphome:
  name: hallway_p1reader
  platform: ESP8266
  board: d1_mini

web_server:
  id: component_web_server
  port: 80

logger:
  id: component_logger
  baud_rate: 0
  level: INFO

mqtt:
  broker: !secret 'mqtt_host'
  username: !secret 'mqtt_user'
  password: !secret 'mqtt_pwd'
  port: 1883

ota:
  id: component_ota

time:
- platform: sntp
  timezone: CET-1CEST,M3.5.0,M10.5.0/3
  id: time_sntp
  update_interval: 15min
  servers:
  - 0.pool.ntp.org
  - 1.pool.ntp.org
  - 2.pool.ntp.org

switch:
- platform: restart
  id: switch_restart
  name: Hallway - P1 Reader Restart
  disabled_by_default: false
  entity_category: config
  icon: mdi:restart

api:
  reboot_timeout: 0s
  port: 6053

wifi:
  id: component_wifi
  networks:
  - ssid: !secret 'wifi_ssid'
    password: !secret 'wifi_pwd'

external_components:
- source:
    url: https://github.com/tube0013/esphome-stream-server-v2.git
    type: git

uart:
- id: uart_bus
  rx_pin:
    number: 3
    mode:
      input: true
      analog: false
      output: false
      open_drain: false
      pullup: false
      pulldown: false
    inverted: false
  baud_rate: 115200
  rx_buffer_size: 1024
  stop_bits: 1
  data_bits: 8
  parity: NONE

stream_server:
- id: ss
  uart_id: uart_bus
  port: 8088

binary_sensor:
- platform: stream_server
  stream_server: ss
  name: Hallway - P1 Reader Serial Connected
```

When using https://github.com/oxan/esphome-stream-server I don't see this error with the same config.
